# Generated by Django 3.2.18 on 2023-03-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20230322_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='post_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
